id: P006768
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1EE31
  title: ལམ་རིམ་ཆེན་མོ།༼སོག་ཡིག༽
  author: ''
  volumes:
    995a2f223b774131816051e55a31c286:
      image_group_id: I1KG16854
      title: ''
      volume_number: 1
      total_pages: 604
      base_file: v001.txt
