id: I46C166AA
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T18:14:25+00:00'
last_modified: '2022-06-08T06:43:30.093172+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1EE31
  title: ལམ་རིམ་ཆེན་མོ།༼སོག་ཡིག༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    C9B9:
      image_group_id: I1KG16854
      title: ''
      total_pages: 604
      order: 1
      base_file: C9B9.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
